language: python
python:
    - '2.7'

install:
    - 'if [ ${TRAVIS_BRANCH} \!= "master" ] && [ -f package/dev_requirements.txt ]; then
        pushd package;
        pip install --extra-index-url https://testpypi.python.org/pypi -r dev_requirements.txt;
        python setup.py develop --no-deps;
        popd;
      else
        pushd package;
        python setup.py install;
        popd;
      fi'
    - pip install -r package/test_requirements.txt
    - pip install coveralls

script:
    - nosetests --with-coverage --cover-package=cloudshell.delphix package/tests

after_success:
    - coveralls
